### ISSUE TITLE
Small questions and fixes

### ISSUE THREAD

**Issue by zertyuiop** [Necrolesian/morrowind-mod-list#1]
- [x] Official Plugins Naturalized - what about High Res Textures?

- [x] Bookart Replacer (PFP Fixes) - new link https://github.com/Sigourn/morrowindsharp/raw/master/mods/Comrade%20Raven's%20Book%20Arts%20(PfP%20Edit).7z

- [x] Bloodmoon Rebalance PFP Patch - Bloodmoon Rebalance already includes it

**Comment by Necrolesian** [comment]
thank you for this report! i've updated the link for bookart replacer pfp fixes

regarding the other items:

- official plugins naturalized: i'm not sure what hi res textures you mean? the included textures are overwritten later by intelligent textures (though for the purposes of this list this only affects the master index texture)

- bloodmoon rebalance: the latest update fixes most inconsistencies with pfp, but not all of them. in particular, the names of a couple draugrs are still all lowercase, and the raven rock spriggans still don't have heartwood. the pfp patch fixes these issues. (the pfp patch does now have several unnecessary records that have been fixed in the latest bloodmoon rebalance, and these records could be removed, but it's not necessary)

**Comment by zertyuiop** [comment]
Bloodmoom PfP Patch is deprecated.
